[workspace]
members = [
  "core",
  "config",
  "ecs",
  "file",
  "lib",
  "pipeline",
  "storage",
  "logging",
  "walker",
  "test_helper",
]
resolver = "2"

[workspace.metadata.workspaces]
no_individual_tags = true

[profile.release]
debug = false
