name: Bump Homebrew formula

on:
  workflow_dispatch:
  # trigger when release got created (preferred)
  release:
    types: [released]
  # trigger on tag push
  # push:
  #   tags:
  #     - "*"- name: Update Homebrew formula
  #
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{secrets.HOMEBREW_XVC_REPOSITORY_TOKEN}}
          # Optional, use the origin repository instead of forking
          no_fork: true
          tap: iesahin/xvc
          # Formula name, required
          formula: xvc
          # Optional, will be determined automatically
          tag: ${{github.ref}}
          # Optional, will be determined automatically
          revision: ${{github.sha}}
          # Optional, if don't want to check for already open PRs
          force: false # true
