name: Release

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "17 17 * * *"
  pull_request:
  #  types: [labeled, review_requested]
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-freebsd
            command: build
            args: "--release --features=bundled-openssl"

          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            command: build
            args: "--release --features=bundled-openssl"

            # FIXME: We need to install libsqlite in some of these targets but this is for later.
          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            command: build
            args: "--release --features=bundled-openssl,bundled-sqlite"

          # FIXME: OpenSSL Compilation Errors
          # - os-name: Linux-riscv64
          #   runs-on: ubuntu-20.04
          #   target: riscv64gc-unknown-linux-gnu
          #   command: build
          #   args: "--release --features=bundled-openssl"

          # gh -R iesahin/xvc run view 12525734325 --log-failed
          # - os-name: Linux-Android
          #   runs-on: ubuntu-22.04
          #   target: aarch64-linux-android
          #   command: build
          #   args: "--release --features=bundled-openssl,bundled-sqlite"

          # gh -R iesahin/xvc run view 12525597866 --log-failed
          # - os-name: NetBSD-x86_64
          #   runs-on: ubuntu-22.04
          #   target: x86_64-unknown-netbsd
          #   command: build
          #   args: "--release --features=bundled-openssl"

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            command: build
            args: "--release --features=bundled-sqlite"

          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            command: build
            args: "--release --features=bundled-sqlite"

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            command: build
            args: "--release"

          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            command: build
            args: "--release"
          # more targets here ...

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: ${{ matrix.platform.args }}
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: xvc
          changes-file: "CHANGELOG.md"
          target: ${{ matrix.platform.target }}
